[project]
name = "intro-to-cs-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Charlie-Ash", email = "charlieash245@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
intro-to-cs-1 = "intro_to_cs_1:main"

[build-system]
requires = ["uv_build>=0.12.16,<0.13.0"]
build-backend = "uv_build"
